version: 2
jobs:
  test:
    working_directory: /home/ubuntu/dotfiles
    docker:
      - image: jtwp470/dotfiles

    steps:
      - checkout
      - run:
          name: Check python version
          command: python3 -V
      - run:
          name: Clone repos from GitHub
          command: python3 install.py download ${CIRCLE_BRANCH}
      - run:
          name: Deploy my code to your home directory
          command: python3 install.py deploy
      - run:
          name: Initializing
          command: python3 install.py init
      - run:
          name: Tests
          command: python3 install.py test
      - run:
          name: Cleaning
          command: python3 install.py clean
      - run:
          name: Run via cURL command
          command: curl -L https://raw.githubusercontent.com/ryosan-470/dotfiles/${CIRCLE_BRANCH}/install.py | python3
      - run:
          name: Run tests
          command: python3 install.py test

  build_and_push:
    docker:
      - image: docker:18.04.0-ce-git
    environment:
      - TAG: jtwp470/dotfiles
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USER --password-stdin
      - run:
          name: Build Docker image
          command: |
            docker pull ${TAG}
            docker build --cache-from ${TAG} -t ${TAG} .
      - deploy:
          name: Push to Docker Hub
          command: |
            docker push ${TAG}

workflows:
  version: 2
  test:
    jobs:
      - test
  build-and-push:
    jobs:
      - test
      - build_and_push:
          requires:
            - test
          filters:
            branches:
              only:
                - master
